#!/bin/bash
#

. /etc/board/rcS

#board entry shell
HOSTNAME_GENERATE_SHELL=hostname-generate.sh
INTERFACES_GENERATE_SHELL=interfaces-generate.sh
CPU_IDENTIFY_SHELL=cpu-identify.sh

#vendor entry shell
APP_ENTRY_SHELL=itl-sys-proc

#customize services

#create soft link 
ln -s -f ${APP_ENTRY_SHELL_PATH}/${APP_ENTRY_SHELL} ${ETC_APP_ENTRY_SHELL_PATH}/S30${ETC_ENTRY_SHELL_VENDOR_PROC_SYS}
#use for app_install_update.sh to call itl-sys-proc
ln -s -f ${APP_ENTRY_SHELL_PATH}/${APP_ENTRY_SHELL} /etc/init.d/${ETC_ENTRY_SHELL_VENDOR_PROC_SYS}
ln -s -f ${BOARD_ENTRY_SHELL_PATH}/${HOSTNAME_GENERATE_SHELL} ${ETC_ENTRY_SHELL_PATH}/S38${HOSTNAME_GENERATE_SHELL}
ln -s -f ${BOARD_ENTRY_SHELL_PATH}/${INTERFACES_GENERATE_SHELL} ${ETC_ENTRY_SHELL_PATH}/S38${INTERFACES_GENERATE_SHELL}
ln -s -f ${BOARD_ENTRY_SHELL_PATH}/${CPU_IDENTIFY_SHELL} ${ETC_ENTRY_SHELL_PATH}/S36${CPU_IDENTIFY_SHELL}

